### ISSUE TITLE
Create typography component

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#10]
![image](https://user-images.githubusercontent.com/1881266/116717226-55f83e00-a9e1-11eb-995e-cce37c0d9aed.png)

Kind of example https://github.com/code4moldova/code4.md/blob/main/components/heading.tsx

https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/cariera.md?node-id=16%3A14

**Comment by Raduc4** [comment]
Assigned to me

**Comment by iamandrewluca** [comment]
Closed in #49 and #60
