### ISSUE TITLE
Create card component and friends

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#15]
https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/cariera.md?node-id=4%3A55

![image](https://user-images.githubusercontent.com/1881266/116718816-0adf2a80-a9e3-11eb-8afe-bd55ad3d8527.png)

**Comment by Raduc4** [comment]
assigned to me

**Comment by Raduc4** [comment]
https://github.com/code4moldova/catalog-profesii/pull/92
