### ISSUE TITLE
Create home page third section

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#29]
![image](https://user-images.githubusercontent.com/1881266/116720131-868da700-a9e4-11eb-81df-6240d800b1b7.png)

https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/cariera.md?node-id=4%3A8664

**Comment by Raduc4** [comment]
Assigned https://github.com/code4moldova/catalog-profesii/pull/62
