### ISSUE TITLE
Create button component

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#4]
First 3 columns are buttons, 4th one is tags

Example https://github.com/code4moldova/code4.md/blob/main/components/button.tsx

![image](https://user-images.githubusercontent.com/1881266/116717057-247f7280-a9e1-11eb-8649-7f79d141480c.png)

https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/cariera.md?node-id=17%3A648

**Comment by Raduc4** [comment]
assigned
