### ISSUE TITLE
Create tag component

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#5]
https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/cariera.md?node-id=17%3A648 (4th column)

![image](https://user-images.githubusercontent.com/1881266/116717333-72947600-a9e1-11eb-9f15-323965b0b802.png)

**Comment by Raduc4** [comment]
assigned https://github.com/code4moldova/catalog-profesii/pull/59
