### ISSUE TITLE
Create hero for guide page

### ISSUE THREAD

**Issue by iamandrewluca** [code4moldova/catalog-profesii#64]
https://www.figma.com/file/gkeUv1Rd9IpOIv7DEHjhUS/profesii.md?node-id=4%3A58

![image](https://user-images.githubusercontent.com/1881266/124393678-43152900-dd04-11eb-95f1-ee3584c0e006.png)

**Comment by Raduc4** [comment]
Assigned to me

**Comment by iamandrewluca** [comment]
Closed in #73
